-- Migration: 005_true_schema_from_live
-- Generated by introspecting the LIVE database (project khzludukwvopshsmgmif)
-- This reflects what is ACTUALLY applied, which had drifted from 001-004.
-- Idempotent where practical (IF NOT EXISTS / DROP POLICY IF EXISTS).

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============ FUNCTIONS ============
CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  INSERT INTO public.clients (id, full_name, email, role)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data ->> 'full_name', split_part(NEW.email, '@', 1)),
    NEW.email,
    COALESCE(NEW.raw_user_meta_data ->> 'role', 'client')
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$function$;

-- ============ TABLES (columns only) ============
CREATE TABLE IF NOT EXISTS public.clients (
  "id" uuid NOT NULL,
  "full_name" text NOT NULL,
  "email" text NOT NULL,
  "phone" text,
  "profile_photo" text,
  "age" integer,
  "gender" text,
  "current_weight" numeric(5,2),
  "target_weight" numeric(5,2),
  "start_weight" numeric(5,2),
  "thyroid_condition" text,
  "medications" text,
  "allergies" text,
  "plan_type" text DEFAULT 'standard'::text,
  "start_date" date DEFAULT CURRENT_DATE,
  "renewal_date" date,
  "coach_notes" text,
  "onboarding_completed" boolean DEFAULT false,
  "subscription_status" text DEFAULT 'active'::text,
  "role" text DEFAULT 'client'::text,
  "streak_current" integer DEFAULT 0,
  "streak_best" integer DEFAULT 0,
  "recovery_score" integer DEFAULT 0,
  "wellness_score" integer DEFAULT 0,
  "tsh_before" numeric(5,2),
  "tsh_current" numeric(5,2),
  "created_at" timestamp with time zone DEFAULT now(),
  "updated_at" timestamp with time zone DEFAULT now(),
  "reminder_day_of_week" integer DEFAULT 0,
  "reminder_time_of_day" time without time zone DEFAULT '18:00:00'::time without time zone,
  "reminder_enabled" boolean DEFAULT true,
  "last_reminder_sent_at" timestamp with time zone
);
CREATE TABLE IF NOT EXISTS public.checkin_feedback (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "checkin_id" uuid NOT NULL,
  "coach_id" uuid NOT NULL,
  "body" text NOT NULL,
  "created_at" timestamp with time zone DEFAULT now(),
  "updated_at" timestamp with time zone DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.coach_insights (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "client_id" uuid NOT NULL,
  "coach_id" uuid,
  "insight" text NOT NULL,
  "is_read" boolean DEFAULT false,
  "created_at" timestamp with time zone DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.daily_habits (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "client_id" uuid NOT NULL,
  "date" date DEFAULT CURRENT_DATE,
  "morning_meds" boolean DEFAULT false,
  "morning_walk" boolean DEFAULT false,
  "hydration_goal" boolean DEFAULT false,
  "meal_prep" boolean DEFAULT false,
  "supplements" boolean DEFAULT false,
  "sleep_by_10pm" boolean DEFAULT false,
  "stress_management" boolean DEFAULT false,
  "created_at" timestamp with time zone DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.email_reminders (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "client_id" uuid NOT NULL,
  "checkin_week" integer NOT NULL,
  "reminder_type" text NOT NULL,
  "sent_at" timestamp with time zone DEFAULT now(),
  "opened_at" timestamp with time zone,
  "click_through" boolean DEFAULT false
);
CREATE TABLE IF NOT EXISTS public.meal_tracking (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "client_id" uuid NOT NULL,
  "date" date DEFAULT CURRENT_DATE,
  "meals_completed" integer DEFAULT 0,
  "hydration" integer DEFAULT 0,
  "supplements_taken" boolean DEFAULT false,
  "calories" integer,
  "protein" integer,
  "carbs" integer,
  "fats" integer,
  "notes" text,
  "created_at" timestamp with time zone DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.plans (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "client_id" uuid NOT NULL,
  "coach_id" uuid NOT NULL,
  "type" text NOT NULL,
  "title" text NOT NULL,
  "content" jsonb NOT NULL,
  "file_path" text,
  "assigned_at" timestamp with time zone DEFAULT now(),
  "updated_at" timestamp with time zone DEFAULT now(),
  "created_at" timestamp with time zone DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.progress_photos (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "client_id" uuid NOT NULL,
  "front_photo" text,
  "side_photo" text,
  "back_photo" text,
  "week_number" integer,
  "notes" text,
  "upload_date" date DEFAULT CURRENT_DATE,
  "created_at" timestamp with time zone DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.testimonials (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "client_id" uuid,
  "client_name" text NOT NULL,
  "testimonial" text NOT NULL,
  "rating" integer,
  "transformation_images" text[],
  "video_review_url" text,
  "weight_lost" numeric(5,2),
  "is_featured" boolean DEFAULT false,
  "is_approved" boolean DEFAULT false,
  "created_at" timestamp with time zone DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.viewed_comparisons (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "client_id" uuid NOT NULL,
  "comparison_key" text NOT NULL,
  "left_session_id" uuid NOT NULL,
  "right_session_id" uuid NOT NULL,
  "created_at" timestamp with time zone DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.weekly_checkins (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "client_id" uuid NOT NULL,
  "week_number" integer NOT NULL,
  "weight" numeric(5,2),
  "waist" numeric(5,2),
  "hips" numeric(5,2),
  "energy_level" integer,
  "sleep_score" integer,
  "stress_level" integer,
  "digestion_score" integer,
  "mood" integer,
  "adherence_score" integer,
  "steps" integer,
  "workouts_completed" integer DEFAULT 0,
  "notes" text,
  "coach_feedback" text,
  "submitted_at" timestamp with time zone DEFAULT now(),
  "created_at" timestamp with time zone DEFAULT now(),
  "bloating" integer,
  "cravings" integer,
  "meds_taken" integer DEFAULT 0,
  "meds_target" integer DEFAULT 0,
  "workouts_target" integer DEFAULT 0,
  "sleep_quality" integer,
  "symptoms" jsonb,
  "reflection_text" text,
  "status" text DEFAULT 'pending'::text
);
CREATE TABLE IF NOT EXISTS public.workout_tracking (
  "id" uuid DEFAULT uuid_generate_v4() NOT NULL,
  "client_id" uuid NOT NULL,
  "date" date DEFAULT CURRENT_DATE,
  "workout_completed" boolean DEFAULT false,
  "workout_type" text,
  "steps" integer DEFAULT 0,
  "duration_minutes" integer DEFAULT 0,
  "calories_burned" integer DEFAULT 0,
  "notes" text,
  "created_at" timestamp with time zone DEFAULT now()
);

-- ============ clients: constraints / indexes / RLS / policies ============
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'clients_email_key' AND conrelid = 'public.clients'::regclass) THEN
    ALTER TABLE public.clients ADD CONSTRAINT "clients_email_key" UNIQUE (email);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'clients_pkey' AND conrelid = 'public.clients'::regclass) THEN
    ALTER TABLE public.clients ADD CONSTRAINT "clients_pkey" PRIMARY KEY (id);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'clients_id_fkey' AND conrelid = 'public.clients'::regclass) THEN
    ALTER TABLE public.clients ADD CONSTRAINT "clients_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'clients_gender_check' AND conrelid = 'public.clients'::regclass) THEN
    ALTER TABLE public.clients ADD CONSTRAINT "clients_gender_check" CHECK ((gender = ANY (ARRAY['male'::text, 'female'::text, 'other'::text])));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'clients_plan_type_check' AND conrelid = 'public.clients'::regclass) THEN
    ALTER TABLE public.clients ADD CONSTRAINT "clients_plan_type_check" CHECK ((plan_type = ANY (ARRAY['standard'::text, 'premium'::text, 'elite'::text])));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'clients_role_check' AND conrelid = 'public.clients'::regclass) THEN
    ALTER TABLE public.clients ADD CONSTRAINT "clients_role_check" CHECK ((role = ANY (ARRAY['client'::text, 'coach'::text, 'admin'::text])));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'clients_subscription_status_check' AND conrelid = 'public.clients'::regclass) THEN
    ALTER TABLE public.clients ADD CONSTRAINT "clients_subscription_status_check" CHECK ((subscription_status = ANY (ARRAY['active'::text, 'paused'::text, 'cancelled'::text, 'expired'::text])));
  END IF;
END $$;
CREATE INDEX IF NOT EXISTS idx_clients_reminder_enabled ON public.clients USING btree (reminder_enabled) WHERE (reminder_enabled = true);
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "clients_delete_own" ON public.clients;
CREATE POLICY "clients_delete_own" ON public.clients AS PERMISSIVE FOR DELETE TO public
  USING ((auth.uid() = id));
DROP POLICY IF EXISTS "clients_insert_own" ON public.clients;
CREATE POLICY "clients_insert_own" ON public.clients AS PERMISSIVE FOR INSERT TO public
  WITH CHECK ((auth.uid() = id));
DROP POLICY IF EXISTS "clients_select_own" ON public.clients;
CREATE POLICY "clients_select_own" ON public.clients AS PERMISSIVE FOR SELECT TO public
  USING ((auth.uid() = id));
DROP POLICY IF EXISTS "coaches_select_all" ON public.clients;
CREATE POLICY "coaches_select_all" ON public.clients AS PERMISSIVE FOR SELECT TO public
  USING ((EXISTS ( SELECT 1
   FROM clients c
  WHERE ((c.id = auth.uid()) AND (c.role = ANY (ARRAY['coach'::text, 'admin'::text]))))));
DROP POLICY IF EXISTS "clients_update_own" ON public.clients;
CREATE POLICY "clients_update_own" ON public.clients AS PERMISSIVE FOR UPDATE TO public
  USING ((auth.uid() = id));
DROP POLICY IF EXISTS "coaches_update_all" ON public.clients;
CREATE POLICY "coaches_update_all" ON public.clients AS PERMISSIVE FOR UPDATE TO public
  USING ((EXISTS ( SELECT 1
   FROM clients c
  WHERE ((c.id = auth.uid()) AND (c.role = ANY (ARRAY['coach'::text, 'admin'::text]))))));

-- ============ checkin_feedback: constraints / indexes / RLS / policies ============
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'checkin_feedback_pkey' AND conrelid = 'public.checkin_feedback'::regclass) THEN
    ALTER TABLE public.checkin_feedback ADD CONSTRAINT "checkin_feedback_pkey" PRIMARY KEY (id);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'checkin_feedback_checkin_id_fkey' AND conrelid = 'public.checkin_feedback'::regclass) THEN
    ALTER TABLE public.checkin_feedback ADD CONSTRAINT "checkin_feedback_checkin_id_fkey" FOREIGN KEY (checkin_id) REFERENCES weekly_checkins(id) ON DELETE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'checkin_feedback_coach_id_fkey' AND conrelid = 'public.checkin_feedback'::regclass) THEN
    ALTER TABLE public.checkin_feedback ADD CONSTRAINT "checkin_feedback_coach_id_fkey" FOREIGN KEY (coach_id) REFERENCES clients(id) ON DELETE CASCADE;
  END IF;
END $$;
CREATE INDEX IF NOT EXISTS idx_checkin_feedback_checkin_id ON public.checkin_feedback USING btree (checkin_id);
CREATE INDEX IF NOT EXISTS idx_checkin_feedback_coach_id ON public.checkin_feedback USING btree (coach_id);
ALTER TABLE public.checkin_feedback DISABLE ROW LEVEL SECURITY;
-- NOTE: RLS is DISABLED on checkin_feedback in the live DB (security gap — not default-deny).

-- ============ coach_insights: constraints / indexes / RLS / policies ============
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'coach_insights_pkey' AND conrelid = 'public.coach_insights'::regclass) THEN
    ALTER TABLE public.coach_insights ADD CONSTRAINT "coach_insights_pkey" PRIMARY KEY (id);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'coach_insights_client_id_fkey' AND conrelid = 'public.coach_insights'::regclass) THEN
    ALTER TABLE public.coach_insights ADD CONSTRAINT "coach_insights_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'coach_insights_coach_id_fkey' AND conrelid = 'public.coach_insights'::regclass) THEN
    ALTER TABLE public.coach_insights ADD CONSTRAINT "coach_insights_coach_id_fkey" FOREIGN KEY (coach_id) REFERENCES clients(id) ON DELETE SET NULL;
  END IF;
END $$;
ALTER TABLE public.coach_insights ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "coaches_insights_insert" ON public.coach_insights;
CREATE POLICY "coaches_insights_insert" ON public.coach_insights AS PERMISSIVE FOR INSERT TO public
  WITH CHECK ((EXISTS ( SELECT 1
   FROM clients c
  WHERE ((c.id = auth.uid()) AND (c.role = ANY (ARRAY['coach'::text, 'admin'::text]))))));
DROP POLICY IF EXISTS "coaches_insights_select" ON public.coach_insights;
CREATE POLICY "coaches_insights_select" ON public.coach_insights AS PERMISSIVE FOR SELECT TO public
  USING ((EXISTS ( SELECT 1
   FROM clients c
  WHERE ((c.id = auth.uid()) AND (c.role = ANY (ARRAY['coach'::text, 'admin'::text]))))));
DROP POLICY IF EXISTS "insights_select_own" ON public.coach_insights;
CREATE POLICY "insights_select_own" ON public.coach_insights AS PERMISSIVE FOR SELECT TO public
  USING ((auth.uid() = client_id));
DROP POLICY IF EXISTS "insights_update_read" ON public.coach_insights;
CREATE POLICY "insights_update_read" ON public.coach_insights AS PERMISSIVE FOR UPDATE TO public
  USING ((auth.uid() = client_id));

-- ============ daily_habits: constraints / indexes / RLS / policies ============
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'daily_habits_client_id_date_key' AND conrelid = 'public.daily_habits'::regclass) THEN
    ALTER TABLE public.daily_habits ADD CONSTRAINT "daily_habits_client_id_date_key" UNIQUE (client_id, date);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'daily_habits_pkey' AND conrelid = 'public.daily_habits'::regclass) THEN
    ALTER TABLE public.daily_habits ADD CONSTRAINT "daily_habits_pkey" PRIMARY KEY (id);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'daily_habits_client_id_fkey' AND conrelid = 'public.daily_habits'::regclass) THEN
    ALTER TABLE public.daily_habits ADD CONSTRAINT "daily_habits_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
  END IF;
END $$;
ALTER TABLE public.daily_habits ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "habits_insert_own" ON public.daily_habits;
CREATE POLICY "habits_insert_own" ON public.daily_habits AS PERMISSIVE FOR INSERT TO public
  WITH CHECK ((auth.uid() = client_id));
DROP POLICY IF EXISTS "coaches_habits_select" ON public.daily_habits;
CREATE POLICY "coaches_habits_select" ON public.daily_habits AS PERMISSIVE FOR SELECT TO public
  USING ((EXISTS ( SELECT 1
   FROM clients c
  WHERE ((c.id = auth.uid()) AND (c.role = ANY (ARRAY['coach'::text, 'admin'::text]))))));
DROP POLICY IF EXISTS "habits_select_own" ON public.daily_habits;
CREATE POLICY "habits_select_own" ON public.daily_habits AS PERMISSIVE FOR SELECT TO public
  USING ((auth.uid() = client_id));
DROP POLICY IF EXISTS "habits_update_own" ON public.daily_habits;
CREATE POLICY "habits_update_own" ON public.daily_habits AS PERMISSIVE FOR UPDATE TO public
  USING ((auth.uid() = client_id));

-- ============ email_reminders: constraints / indexes / RLS / policies ============
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'email_reminders_pkey' AND conrelid = 'public.email_reminders'::regclass) THEN
    ALTER TABLE public.email_reminders ADD CONSTRAINT "email_reminders_pkey" PRIMARY KEY (id);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'email_reminders_client_id_fkey' AND conrelid = 'public.email_reminders'::regclass) THEN
    ALTER TABLE public.email_reminders ADD CONSTRAINT "email_reminders_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
  END IF;
END $$;
CREATE INDEX IF NOT EXISTS idx_email_reminders_client_id ON public.email_reminders USING btree (client_id);
CREATE INDEX IF NOT EXISTS idx_email_reminders_type ON public.email_reminders USING btree (reminder_type);
CREATE INDEX IF NOT EXISTS idx_email_reminders_week ON public.email_reminders USING btree (checkin_week);
ALTER TABLE public.email_reminders DISABLE ROW LEVEL SECURITY;
-- NOTE: RLS is DISABLED on email_reminders in the live DB (security gap — not default-deny).

-- ============ meal_tracking: constraints / indexes / RLS / policies ============
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'meal_tracking_pkey' AND conrelid = 'public.meal_tracking'::regclass) THEN
    ALTER TABLE public.meal_tracking ADD CONSTRAINT "meal_tracking_pkey" PRIMARY KEY (id);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'meal_tracking_client_id_fkey' AND conrelid = 'public.meal_tracking'::regclass) THEN
    ALTER TABLE public.meal_tracking ADD CONSTRAINT "meal_tracking_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'meal_tracking_meals_completed_check' AND conrelid = 'public.meal_tracking'::regclass) THEN
    ALTER TABLE public.meal_tracking ADD CONSTRAINT "meal_tracking_meals_completed_check" CHECK (((meals_completed >= 0) AND (meals_completed <= 6)));
  END IF;
END $$;
ALTER TABLE public.meal_tracking ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "meals_delete_own" ON public.meal_tracking;
CREATE POLICY "meals_delete_own" ON public.meal_tracking AS PERMISSIVE FOR DELETE TO public
  USING ((auth.uid() = client_id));
DROP POLICY IF EXISTS "meals_insert_own" ON public.meal_tracking;
CREATE POLICY "meals_insert_own" ON public.meal_tracking AS PERMISSIVE FOR INSERT TO public
  WITH CHECK ((auth.uid() = client_id));
DROP POLICY IF EXISTS "coaches_meals_select" ON public.meal_tracking;
CREATE POLICY "coaches_meals_select" ON public.meal_tracking AS PERMISSIVE FOR SELECT TO public
  USING ((EXISTS ( SELECT 1
   FROM clients c
  WHERE ((c.id = auth.uid()) AND (c.role = ANY (ARRAY['coach'::text, 'admin'::text]))))));
DROP POLICY IF EXISTS "meals_select_own" ON public.meal_tracking;
CREATE POLICY "meals_select_own" ON public.meal_tracking AS PERMISSIVE FOR SELECT TO public
  USING ((auth.uid() = client_id));
DROP POLICY IF EXISTS "meals_update_own" ON public.meal_tracking;
CREATE POLICY "meals_update_own" ON public.meal_tracking AS PERMISSIVE FOR UPDATE TO public
  USING ((auth.uid() = client_id));

-- ============ plans: constraints / indexes / RLS / policies ============
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'plans_pkey' AND conrelid = 'public.plans'::regclass) THEN
    ALTER TABLE public.plans ADD CONSTRAINT "plans_pkey" PRIMARY KEY (id);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'plans_client_id_fkey' AND conrelid = 'public.plans'::regclass) THEN
    ALTER TABLE public.plans ADD CONSTRAINT "plans_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'plans_coach_id_fkey' AND conrelid = 'public.plans'::regclass) THEN
    ALTER TABLE public.plans ADD CONSTRAINT "plans_coach_id_fkey" FOREIGN KEY (coach_id) REFERENCES clients(id);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'plans_type_check' AND conrelid = 'public.plans'::regclass) THEN
    ALTER TABLE public.plans ADD CONSTRAINT "plans_type_check" CHECK ((type = ANY (ARRAY['meal'::text, 'workout'::text])));
  END IF;
END $$;
CREATE INDEX IF NOT EXISTS idx_plans_client_id ON public.plans USING btree (client_id);
CREATE INDEX IF NOT EXISTS idx_plans_client_type ON public.plans USING btree (client_id, type);
CREATE INDEX IF NOT EXISTS idx_plans_coach_id ON public.plans USING btree (coach_id);
CREATE INDEX IF NOT EXISTS idx_plans_updated_at ON public.plans USING btree (updated_at DESC);
ALTER TABLE public.plans ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "coaches_delete_plans" ON public.plans;
CREATE POLICY "coaches_delete_plans" ON public.plans AS PERMISSIVE FOR DELETE TO public
  USING ((coach_id = auth.uid()));
DROP POLICY IF EXISTS "coaches_insert_plans" ON public.plans;
CREATE POLICY "coaches_insert_plans" ON public.plans AS PERMISSIVE FOR INSERT TO public
  WITH CHECK (((coach_id = auth.uid()) AND (EXISTS ( SELECT 1
   FROM clients
  WHERE ((clients.id = auth.uid()) AND (clients.role = 'coach'::text))))));
DROP POLICY IF EXISTS "clients_select_own_plans" ON public.plans;
CREATE POLICY "clients_select_own_plans" ON public.plans AS PERMISSIVE FOR SELECT TO public
  USING ((client_id = auth.uid()));
DROP POLICY IF EXISTS "coaches_select_client_plans" ON public.plans;
CREATE POLICY "coaches_select_client_plans" ON public.plans AS PERMISSIVE FOR SELECT TO public
  USING (((coach_id = auth.uid()) OR (EXISTS ( SELECT 1
   FROM clients coach_rel
  WHERE ((coach_rel.id = auth.uid()) AND (coach_rel.role = 'coach'::text) AND (coach_rel.id = plans.coach_id))))));
DROP POLICY IF EXISTS "coaches_update_plans" ON public.plans;
CREATE POLICY "coaches_update_plans" ON public.plans AS PERMISSIVE FOR UPDATE TO public
  USING ((coach_id = auth.uid()))
  WITH CHECK ((coach_id = auth.uid()));

-- ============ progress_photos: constraints / indexes / RLS / policies ============
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'progress_photos_pkey' AND conrelid = 'public.progress_photos'::regclass) THEN
    ALTER TABLE public.progress_photos ADD CONSTRAINT "progress_photos_pkey" PRIMARY KEY (id);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'progress_photos_client_id_fkey' AND conrelid = 'public.progress_photos'::regclass) THEN
    ALTER TABLE public.progress_photos ADD CONSTRAINT "progress_photos_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
  END IF;
END $$;
ALTER TABLE public.progress_photos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "photos_delete_own" ON public.progress_photos;
CREATE POLICY "photos_delete_own" ON public.progress_photos AS PERMISSIVE FOR DELETE TO public
  USING ((auth.uid() = client_id));
DROP POLICY IF EXISTS "photos_insert_own" ON public.progress_photos;
CREATE POLICY "photos_insert_own" ON public.progress_photos AS PERMISSIVE FOR INSERT TO public
  WITH CHECK ((auth.uid() = client_id));
DROP POLICY IF EXISTS "coaches_photos_select" ON public.progress_photos;
CREATE POLICY "coaches_photos_select" ON public.progress_photos AS PERMISSIVE FOR SELECT TO public
  USING ((EXISTS ( SELECT 1
   FROM clients c
  WHERE ((c.id = auth.uid()) AND (c.role = ANY (ARRAY['coach'::text, 'admin'::text]))))));
DROP POLICY IF EXISTS "photos_select_own" ON public.progress_photos;
CREATE POLICY "photos_select_own" ON public.progress_photos AS PERMISSIVE FOR SELECT TO public
  USING ((auth.uid() = client_id));
DROP POLICY IF EXISTS "photos_update_own" ON public.progress_photos;
CREATE POLICY "photos_update_own" ON public.progress_photos AS PERMISSIVE FOR UPDATE TO public
  USING ((auth.uid() = client_id));

-- ============ testimonials: constraints / indexes / RLS / policies ============
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'testimonials_pkey' AND conrelid = 'public.testimonials'::regclass) THEN
    ALTER TABLE public.testimonials ADD CONSTRAINT "testimonials_pkey" PRIMARY KEY (id);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'testimonials_client_id_fkey' AND conrelid = 'public.testimonials'::regclass) THEN
    ALTER TABLE public.testimonials ADD CONSTRAINT "testimonials_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'testimonials_rating_check' AND conrelid = 'public.testimonials'::regclass) THEN
    ALTER TABLE public.testimonials ADD CONSTRAINT "testimonials_rating_check" CHECK (((rating >= 1) AND (rating <= 5)));
  END IF;
END $$;
ALTER TABLE public.testimonials ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "coaches_testimonials_all" ON public.testimonials;
CREATE POLICY "coaches_testimonials_all" ON public.testimonials AS PERMISSIVE FOR ALL TO public
  USING ((EXISTS ( SELECT 1
   FROM clients c
  WHERE ((c.id = auth.uid()) AND (c.role = ANY (ARRAY['coach'::text, 'admin'::text]))))));
DROP POLICY IF EXISTS "testimonials_insert_own" ON public.testimonials;
CREATE POLICY "testimonials_insert_own" ON public.testimonials AS PERMISSIVE FOR INSERT TO public
  WITH CHECK ((auth.uid() = client_id));
DROP POLICY IF EXISTS "testimonials_public_read" ON public.testimonials;
CREATE POLICY "testimonials_public_read" ON public.testimonials AS PERMISSIVE FOR SELECT TO public
  USING ((is_approved = true));

-- ============ viewed_comparisons: constraints / indexes / RLS / policies ============
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'viewed_comparisons_pkey' AND conrelid = 'public.viewed_comparisons'::regclass) THEN
    ALTER TABLE public.viewed_comparisons ADD CONSTRAINT "viewed_comparisons_pkey" PRIMARY KEY (id);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'viewed_comparisons_client_id_fkey' AND conrelid = 'public.viewed_comparisons'::regclass) THEN
    ALTER TABLE public.viewed_comparisons ADD CONSTRAINT "viewed_comparisons_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'viewed_comparisons_left_session_id_fkey' AND conrelid = 'public.viewed_comparisons'::regclass) THEN
    ALTER TABLE public.viewed_comparisons ADD CONSTRAINT "viewed_comparisons_left_session_id_fkey" FOREIGN KEY (left_session_id) REFERENCES progress_photos(id) ON DELETE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'viewed_comparisons_right_session_id_fkey' AND conrelid = 'public.viewed_comparisons'::regclass) THEN
    ALTER TABLE public.viewed_comparisons ADD CONSTRAINT "viewed_comparisons_right_session_id_fkey" FOREIGN KEY (right_session_id) REFERENCES progress_photos(id) ON DELETE CASCADE;
  END IF;
END $$;
CREATE INDEX IF NOT EXISTS idx_viewed_comparisons_client_id ON public.viewed_comparisons USING btree (client_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_viewed_comparisons_unique ON public.viewed_comparisons USING btree (client_id, comparison_key);
ALTER TABLE public.viewed_comparisons DISABLE ROW LEVEL SECURITY;
-- NOTE: RLS is DISABLED on viewed_comparisons in the live DB (security gap — not default-deny).

-- ============ weekly_checkins: constraints / indexes / RLS / policies ============
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'weekly_checkins_pkey' AND conrelid = 'public.weekly_checkins'::regclass) THEN
    ALTER TABLE public.weekly_checkins ADD CONSTRAINT "weekly_checkins_pkey" PRIMARY KEY (id);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'weekly_checkins_client_id_fkey' AND conrelid = 'public.weekly_checkins'::regclass) THEN
    ALTER TABLE public.weekly_checkins ADD CONSTRAINT "weekly_checkins_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'weekly_checkins_adherence_score_check' AND conrelid = 'public.weekly_checkins'::regclass) THEN
    ALTER TABLE public.weekly_checkins ADD CONSTRAINT "weekly_checkins_adherence_score_check" CHECK (((adherence_score >= 0) AND (adherence_score <= 100)));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'weekly_checkins_bloating_check' AND conrelid = 'public.weekly_checkins'::regclass) THEN
    ALTER TABLE public.weekly_checkins ADD CONSTRAINT "weekly_checkins_bloating_check" CHECK (((bloating >= 1) AND (bloating <= 10)));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'weekly_checkins_cravings_check' AND conrelid = 'public.weekly_checkins'::regclass) THEN
    ALTER TABLE public.weekly_checkins ADD CONSTRAINT "weekly_checkins_cravings_check" CHECK (((cravings >= 1) AND (cravings <= 10)));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'weekly_checkins_digestion_score_check' AND conrelid = 'public.weekly_checkins'::regclass) THEN
    ALTER TABLE public.weekly_checkins ADD CONSTRAINT "weekly_checkins_digestion_score_check" CHECK (((digestion_score >= 1) AND (digestion_score <= 10)));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'weekly_checkins_energy_level_check' AND conrelid = 'public.weekly_checkins'::regclass) THEN
    ALTER TABLE public.weekly_checkins ADD CONSTRAINT "weekly_checkins_energy_level_check" CHECK (((energy_level >= 1) AND (energy_level <= 10)));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'weekly_checkins_mood_check' AND conrelid = 'public.weekly_checkins'::regclass) THEN
    ALTER TABLE public.weekly_checkins ADD CONSTRAINT "weekly_checkins_mood_check" CHECK (((mood >= 1) AND (mood <= 10)));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'weekly_checkins_sleep_quality_check' AND conrelid = 'public.weekly_checkins'::regclass) THEN
    ALTER TABLE public.weekly_checkins ADD CONSTRAINT "weekly_checkins_sleep_quality_check" CHECK (((sleep_quality >= 1) AND (sleep_quality <= 10)));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'weekly_checkins_sleep_score_check' AND conrelid = 'public.weekly_checkins'::regclass) THEN
    ALTER TABLE public.weekly_checkins ADD CONSTRAINT "weekly_checkins_sleep_score_check" CHECK (((sleep_score >= 1) AND (sleep_score <= 10)));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'weekly_checkins_status_check' AND conrelid = 'public.weekly_checkins'::regclass) THEN
    ALTER TABLE public.weekly_checkins ADD CONSTRAINT "weekly_checkins_status_check" CHECK ((status = ANY (ARRAY['pending'::text, 'submitted'::text, 'reviewed'::text])));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'weekly_checkins_stress_level_check' AND conrelid = 'public.weekly_checkins'::regclass) THEN
    ALTER TABLE public.weekly_checkins ADD CONSTRAINT "weekly_checkins_stress_level_check" CHECK (((stress_level >= 1) AND (stress_level <= 10)));
  END IF;
END $$;
CREATE INDEX IF NOT EXISTS idx_weekly_checkins_client_week ON public.weekly_checkins USING btree (client_id, week_number DESC);
ALTER TABLE public.weekly_checkins ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "checkins_delete_own" ON public.weekly_checkins;
CREATE POLICY "checkins_delete_own" ON public.weekly_checkins AS PERMISSIVE FOR DELETE TO public
  USING ((auth.uid() = client_id));
DROP POLICY IF EXISTS "checkins_insert_own" ON public.weekly_checkins;
CREATE POLICY "checkins_insert_own" ON public.weekly_checkins AS PERMISSIVE FOR INSERT TO public
  WITH CHECK ((auth.uid() = client_id));
DROP POLICY IF EXISTS "checkins_select_own" ON public.weekly_checkins;
CREATE POLICY "checkins_select_own" ON public.weekly_checkins AS PERMISSIVE FOR SELECT TO public
  USING ((auth.uid() = client_id));
DROP POLICY IF EXISTS "coaches_checkins_select" ON public.weekly_checkins;
CREATE POLICY "coaches_checkins_select" ON public.weekly_checkins AS PERMISSIVE FOR SELECT TO public
  USING ((EXISTS ( SELECT 1
   FROM clients c
  WHERE ((c.id = auth.uid()) AND (c.role = ANY (ARRAY['coach'::text, 'admin'::text]))))));
DROP POLICY IF EXISTS "checkins_update_own" ON public.weekly_checkins;
CREATE POLICY "checkins_update_own" ON public.weekly_checkins AS PERMISSIVE FOR UPDATE TO public
  USING ((auth.uid() = client_id));
DROP POLICY IF EXISTS "coaches_checkins_update" ON public.weekly_checkins;
CREATE POLICY "coaches_checkins_update" ON public.weekly_checkins AS PERMISSIVE FOR UPDATE TO public
  USING ((EXISTS ( SELECT 1
   FROM clients c
  WHERE ((c.id = auth.uid()) AND (c.role = ANY (ARRAY['coach'::text, 'admin'::text]))))));

-- ============ workout_tracking: constraints / indexes / RLS / policies ============
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'workout_tracking_pkey' AND conrelid = 'public.workout_tracking'::regclass) THEN
    ALTER TABLE public.workout_tracking ADD CONSTRAINT "workout_tracking_pkey" PRIMARY KEY (id);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'workout_tracking_client_id_fkey' AND conrelid = 'public.workout_tracking'::regclass) THEN
    ALTER TABLE public.workout_tracking ADD CONSTRAINT "workout_tracking_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
  END IF;
END $$;
ALTER TABLE public.workout_tracking ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "workouts_delete_own" ON public.workout_tracking;
CREATE POLICY "workouts_delete_own" ON public.workout_tracking AS PERMISSIVE FOR DELETE TO public
  USING ((auth.uid() = client_id));
DROP POLICY IF EXISTS "workouts_insert_own" ON public.workout_tracking;
CREATE POLICY "workouts_insert_own" ON public.workout_tracking AS PERMISSIVE FOR INSERT TO public
  WITH CHECK ((auth.uid() = client_id));
DROP POLICY IF EXISTS "coaches_workouts_select" ON public.workout_tracking;
CREATE POLICY "coaches_workouts_select" ON public.workout_tracking AS PERMISSIVE FOR SELECT TO public
  USING ((EXISTS ( SELECT 1
   FROM clients c
  WHERE ((c.id = auth.uid()) AND (c.role = ANY (ARRAY['coach'::text, 'admin'::text]))))));
DROP POLICY IF EXISTS "workouts_select_own" ON public.workout_tracking;
CREATE POLICY "workouts_select_own" ON public.workout_tracking AS PERMISSIVE FOR SELECT TO public
  USING ((auth.uid() = client_id));
DROP POLICY IF EXISTS "workouts_update_own" ON public.workout_tracking;
CREATE POLICY "workouts_update_own" ON public.workout_tracking AS PERMISSIVE FOR UPDATE TO public
  USING ((auth.uid() = client_id));

-- ============ TRIGGERS ============
CREATE OR REPLACE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION handle_new_user();
CREATE OR REPLACE TRIGGER update_clients_updated_at BEFORE UPDATE ON public.clients FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
